### ISSUE TITLE
I hace a problem with the wallpaper.

### ISSUE THREAD

**Issue by doldor** [hayyaoe/zenities#16]
It is very nice, but I have a problem, when I log in, the wallpaper is gray, and I can not see anything, only the mouse pointer, is there any way I can communicate with you, so you can help me?
![17341560618123025092516707274677](https://github.com/user-attachments/assets/84378b7d-05a8-41b8-9a90-c5d72b11165d)

**Comment by hayyaoe** [comment]
I think this is caused by the install script, did the issue happen after you install the rice ?

**Comment by doldor** [comment]
Yes, it happened after I installed it with the script, is there another way to install it? I'm really interested in installing your rice, it looks very good, my discord is doldor.

**Comment by doldor** [comment]
✓
