### ISSUE TITLE
May I ask what font your eww is using?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [hayyaoe/zenities#2]
![1](https://github.com/user-attachments/assets/8481b864-eb21-4047-b545-74ebafa6e5e6)

https://github.com/search?q=repo%3Ahayyaoe%2Fzenities+.cache&type=code

When using your configuration files, I encountered some issues. You referenced files from ~/.cache/ in some configuration files, but these files are not provided in the project. When I move my mouse over the volume icon, the volume adjustment settings do not appear. Similarly, other icons on the bar do not respond either.

**Comment by hayyaoe** [comment]
the cache is from pywal that generates custom colors, of you want to use it you can install pywal, and the font im using for the eww is ttf-mononoki, and for the icons otf-hermit-nerd. Hope that helps 🙌

**Comment by hayyaoe** [comment]
the eww is also has dependencies on Light for the brigthness, and pactl for volume hope that helps.
