### ISSUE TITLE
Open windows in the youtube video

### ISSUE THREAD

**Issue by exoquinni** [hayyaoe/zenities#20]
I was just wondering what the names were of all the windows you had open in the youtube video that you posted as well as how to open them. Specifically the matrix window, visualizer, and device specs.

sorry if this is common knowledge I’m fairly new to linux
![IMG_4958](https://github.com/user-attachments/assets/d51e570d-1153-4b80-a879-df4675499efd)
![IMG_4959](https://github.com/user-attachments/assets/825d5dc1-4178-4b87-8771-b01730009e6f)

**Comment by hayyaoe** [comment]
no problem, the matrix can be open with the command `cmatrix`, the visualizer `cava` and the device monitor `btm`
