### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by Foeder** [hayyaoe/zenities#7]
Hello!
I recently installed your rice on Arch and I had a rather stupid question, but I really don’t understand how to do it. The screenshot shows two small windows with information about the system and a folder with wallpapers. How can I do the same?
sorry for the stupid questions.

**Comment by hayyaoe** [comment]
the information about the system is neofetch, neofetch is shown everytime you open a terminal in floating mode by using `SUPER + SHIFT +  RETURN` or windows + shift + enter if you use windows layout keyboard, or you could just run thr command `neofetch` in the terminal. for the file manager you can use the key combo `SUPER + SHIFT + M` to open it, or cou could run the command `yazi` in the terminal. to resize the window you could hold the `SUPER` key the right click and drag your cursor, to move the window you could use `SUPER` then left click. 

let me know if the instructions aren't clear enough 👍👍

**Comment by Foeder** [comment]
Thank you so much!!!!!!!
